# Generated by Django 2.2.1 on 2019-05-26 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='saved',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs ayant sauvegardés ce produit'),
        ),
    ]
