# Generated by Django 2.2.1 on 2019-05-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190526_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'article'},
        ),
        migrations.AddField(
            model_name='product',
            name='carbohydrates',
            field=models.FloatField(default=0, verbose_name='Glucides pour 100g'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='r', verbose_name='Catégories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='energy',
            field=models.FloatField(default=0, verbose_name='Valeur energétique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.FloatField(default=0, verbose_name='Gras pour 100g'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_small_url',
            field=models.URLField(default='r', unique=True, verbose_name="URL de l'image du produit (Thumbnail)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='r', unique=True, verbose_name="URL de l'image du produit"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nutriscore',
            field=models.CharField(default='r', max_length=1, verbose_name='Score nutritionnel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.FloatField(default=0, verbose_name='Protéines pour 100g'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='salt',
            field=models.FloatField(default=0, verbose_name='Sels pour 100g'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fat',
            field=models.FloatField(default=0, verbose_name='Acides gras saturés pour 100g'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sodium',
            field=models.FloatField(default=0, verbose_name='Sodium pour 100g'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.CharField(max_length=100, null=True, verbose_name='Magasins'),
        ),
        migrations.AddField(
            model_name='product',
            name='sugar',
            field=models.FloatField(default=0, verbose_name='Sucres pour 100g'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default='r', unique=True, verbose_name='URL du produit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom du produit'),
        ),
    ]
