# Generated by Django 2.2.1 on 2019-05-27 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190527_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'produit', 'verbose_name_plural': 'produits'},
        ),
        migrations.AlterField(
            model_name='product',
            name='saved',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs ayant sauvegardés ce produit'),
        ),
    ]
