# Generated by Django 2.2.1 on 2019-05-27 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190527_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='saved',
            field=models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs ayant sauvegardés ce produit'),
        ),
    ]
