# Generated by Django 2.2.1 on 2019-05-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190527_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stores',
            field=models.CharField(max_length=200, null=True, verbose_name='Magasins'),
        ),
    ]
